### ISSUE TITLE
the Resolution is quite low, is it possible to adjust resolution? 

### ISSUE THREAD

**Issue by 1c7** [w-okada/screen-recorder-ts#1]
https://user-images.githubusercontent.com/1804755/224976742-340d11da-8ace-4bcf-8f5b-6ff327879b16.mp4

**Comment by 1c7** [comment]
make it 4k (or the max resolution my screen can provider 3024 x 1964)

**Comment by 1c7** [comment]
this look like 1080p

**Comment by 1c7** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/1804755/224977758-70157275-0c8c-4e0b-a854-984e2a0a29c6.png">
1512x982

**Comment by w-okada** [comment]
OK, I fixed.
Demo can capture up to 3840 x 2160.

**Comment by 1c7** [comment]
Thank you!
